// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylvhhlykyojudldcmzou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlsdmhobHlreW9qdWRsZGNtem91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQwMjkzNzUsImV4cCI6MjA5OTYwNTM3NX0.iiSRHo_fnDvFHtwEYPGXPHr7YYw6HeWU-LHKL1u2heM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// NOTE: Typed as SupabaseClient<any> because the generated `Database` type in
// ./types.ts is out-of-date with the migrated schema (many tables/RPCs are
// missing). Using `any` here unblocks the codebase; regenerate types.ts to
// restore full type safety.
export const supabase: SupabaseClient<any, 'public', any> = createClient<any>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Keep the Database import referenced so tooling doesn't drop it.
export type { Database };
